name       : python-werkzeug
version    : 0.14.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/W/Werkzeug/Werkzeug-0.14.1.tar.gz : c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c
license    : BSD-3-Clause
component  : programming.python
summary    : The Swiss Army knife of Python web development
description: |
    The Swiss Army knife of Python web development
builddeps  :
    - python-pytest
    - python-requests
    - python-setuptools
    - python-termcolor
    - python-watchdog
rundeps    :
    - python-termcolor
    - python-watchdog
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test -k "not test_monkeypached_sleep"
    popd
    pushd $PKG_BUILD_DIR/py3build
        py.test3 -k "not test_monkeypached_sleep"
    popd
