name       : python-werkzeug
version    : 0.11.11
release    : 1
source     :
    - https://pypi.python.org/packages/43/2e/d822b4a4216804519ace92e0368dcfc4b0b2887462d852fdd476b253ecc9/Werkzeug-0.11.11.tar.gz : e72c46bc14405cba7a26bd2ce28df734471bc9016bc8b4cb69466c2c14c2f7e5
license    : BSD-3-Clause
component  : programming.python
summary    : The Swiss Army knife of Python web development
description: |
    The Swiss Army knife of Python web development
builddeps  :
    - python-setuptools
    - python-termcolor
    - python-watchdog
rundeps    :
    - python-termcolor
    - python-watchdog
build      : |
    %python_setup    
install    : |
    %python_install
