name       : python-werkzeug
version    : 2.0.2
release    : 6
source     :
    - https://github.com/pallets/werkzeug/archive/refs/tags/2.0.2.tar.gz : a963c274c8d879c4cc08c2b7fe9b4ba18e172078db97593a1436f1ad9a49407d
license    : BSD-3-Clause
component  : programming.python
summary    : The Swiss Army knife of Python web development
description: |
    The Swiss Army knife of Python web development
builddeps  :
    - python-pytest
    - python-requests
    - python-termcolor
    - python-watchdog
rundeps    :
    - python-termcolor
    - python-watchdog
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#   needs newer pytest
#   %python3_test py.test3 -k "not test_monkeypached_sleep"
