name       : python-werkzeug
version    : 2.1.2
release    : 8
source     :
    - https://github.com/pallets/werkzeug/archive/refs/tags/2.1.2.tar.gz : 5031cb388f7c5bbb28609d7f6bfd16380ce303f2a93cee2b27717fd0e2adda5d
homepage   : https://palletsprojects.com/p/werkzeug/
license    : BSD-3-Clause
component  : programming.python
summary    : The Swiss Army knife of Python web development
description: |
    Werkzeug is a comprehensive WSGI web application library. It began as a simple collection of various utilities for WSGI applications and has become one of the most advanced WSGI utility libraries. Flask wraps Werkzeug, using it to handle the details of WSGI while providing more structure and patterns for defining powerful applications.
builddeps  :
    - python-pytest    # check
    - python-requests  # check
    - python-termcolor # check
    - python-watchdog  # check
rundeps    :
    - python-termcolor
    - python-watchdog
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#   # needs python-ephemeral-port-reserve and python-pytest-xprocess
#   %python3_test pytest3 -k "not test_monkeypached_sleep"
